# Generated by Django 3.2.19 on 2025-08-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Projektcode', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(help_text='Eindeutige Nummer des Messobjekts', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('messbedingungen', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekte', to='messung.projekt')),
            ],
            options={
                'unique_together': {('projekt', 'nummer')},
            },
        ),
        migrations.CreateModel(
            name='Messdaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Einzelmessung' oder 'Sequenz 1'", max_length=100)),
                ('messdaten', models.JSONField(default=dict, help_text='Dictionary von {timestamp: messwert}')),
                ('min_wert', models.FloatField(blank=True, null=True)),
                ('max_wert', models.FloatField(blank=True, null=True)),
                ('avg_wert', models.FloatField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messungen', to='messung.objekt')),
            ],
        ),
    ]
