# Generated by Django 3.2.19 on 2025-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdaten',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messdaten',
            name='name',
            field=models.CharField(help_text="z.B. 'Einzelmessung' oder der Name der Sequenz", max_length=100),
        ),
    ]
