# Generated by Django 3.2.19 on 2025-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messung', '0002_auto_20250804_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messdaten',
            name='messdaten',
            field=models.JSONField(default=list, help_text='Liste von Messpunkten'),
        ),
        migrations.AlterField(
            model_name='messdaten',
            name='name',
            field=models.CharField(help_text="Name der Messung (z.B. 'Einzelmessung' oder Sequenzname)", max_length=100),
        ),
    ]
