# Generated by Django 3.2.19 on 2025-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messung', '0003_auto_20250804_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdaten',
            name='u0',
            field=models.FloatField(blank=True, help_text='Gleichmässigkeit (min/avg)', null=True),
        ),
    ]
