# Generated by Django 3.2.19 on 2025-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messung', '0004_messdaten_u0'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdaten',
            name='device',
            field=models.CharField(blank=True, help_text='Informationen zum Messgerät', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messdaten',
            name='einheit',
            field=models.CharField(blank=True, help_text='Messeinheit der Werte', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messdaten',
            name='name',
            field=models.CharField(help_text='Name der Messung', max_length=100),
        ),
    ]
