# Generated by Django 3.2.19 on 2025-08-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messung', '0005_auto_20250806_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anforderungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('typ', models.TextField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('avgmod', models.FloatField(blank=True, null=True)),
                ('u0', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='objekt',
            name='messbedingungen',
        ),
        migrations.AddField(
            model_name='messdaten',
            name='messbedingungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messdaten',
            name='messhoehe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messdaten',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messdaten',
            name='einheit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messdaten',
            name='anforderung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messung.anforderungen'),
        ),
    ]
